---
title: "Bioc/AnVIL binary generation"
author: "Bioc/AnVIL team"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Bioc/AnVIL binary generation}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

Binary packages for fast installation via `AnVIL::install()` for Bioconductor
and CRAN packages are available at through a `CRAN`-style repository at
`https://storage.googleapis.com/bioconductor_docker/packages`. The packages are
generated with the internal Bioconductor package,
[BiocKubeInstall](https://github.com/Bioconductor/BiocKubeInstall), which
parallelizes package installation and binary creation on a Kubernetes cluster
using Google Kubernetes Engine. The clusters runs and deploys builds Tuesday,
Thursdays, and Saturday through a scheduled Github Action. See the [BiocKubeInstall
Documentation](https://bioconductor.github.io/BiocKubeInstall) for more information.

BiocKubeInstall works with [Bioconductor/k8sredis](https://github.com/Bioconductor/k8sredis),
which facilitations parallelization over a Kubernetes cluster. Docker images for
`bioc-redis-manager` and `bioc-redis-worker` on Docker Hub.

## Additional Resources
- [Slides](https://docs.google.com/presentation/d/1Y7g_6X8I6DPaNK84EzWNo1wVpfAwdORGt6kcgcPYOV4/edit?usp=sharing)
- [shwetagopaul92/hgvarByKub](https://github.com/shwetagopaul92/hgvarByKub) - an example of R
  and Kubernetes
