---
title: "Bioc/AnVIL containers"
shorttitle: "testing pkgdown approach"
author: "Bioc/AnVIL containers"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{AnVIL administration site}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: no
    theme: united
    toc: yes
---


## Containers

<a name="containers"></a>

The latest terra-jupyter-bioconductor docker containers are available
at [AnVIL][] and on the Google Container Registry ([gcr][]). They work
like the [bioconductor_docker][] images, with the capability to
install 'all of' _Bioconductor_ packages along with a few
pre-installed "core" set of packages. The terra-jupyter-bioconductor
image inherits from the terra-jupyter-r image which has all the system
dependencies installed. This image has been tested on Leonardo and
installs all but a few packages in _Bioconductor_ release,which
fail due to achived CRAN dependencies.

- Jupyter notebooks

The images are based on _R_ version 4.0 and _Bioconductor_ version
3.12.

    - [image][terra-jupyter-bioconductor:image], [github][terra-jupyter-bioconductor:github], _Bioconductor_ [github][terra-jupyter-bioconductor:github] (use for _Bioconductor_-specific issues).

- RStudio / _Bioconductor_

The image now has R-4.0.3 and the latest stable release Bioc 3.12.

    - [image][anvil-rstudio-bioconductor:image], [github][anvil-rstudio-bioconductor:github].

    - The terra-rstudio-bioconductor docker container is currently available as a custom 'bring your own' image to terra while work on a fully integrated RStudio environment is being developed.

